config/routes.rb
Rails.application.routes.draw do
  resources :reviews do
    resources :comments, :only => [:create, :destroy]
  end

  root 'home#index'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :review
end

app/models/review.rb
class Review < ActiveRecord::Base
  has_many :comments
  accepts_nested_attributes_for :comments

  def display_name
    title.upcase
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @review = Review.find(params[:review_id])
    @review.comments.create(comment_params)
    redirect_to @review, notice: "Comment successful."
  end

  def destroy
    @review = Review.find(params[:review_id])
    @comment = @review.comments.find(params[:id])
    @comment.destroy

    redirect_to @review, notice: "Comment deleted."
  end

  private

  def comment_params
    params.require(:comment).permit(:author, :body)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    @reviews = Review.all
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_review, only: [:show, :edit, :update, :destroy]

  # GET /reviews
  def index
    @reviews = Review.all
  end

  # GET /reviews/1
  def show
  end

  # GET /reviews/new
  def new
    @review = Review.new
  end

  # GET /reviews/1/edit
  def edit
  end

  # POST /reviews
  def create
    @review = Review.new(review_params)

    if @review.save
      redirect_to @review, notice: 'Review was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /reviews/1
  def update
    if @review.update(review_params)
      redirect_to @review, notice: 'Review was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /reviews/1
  def destroy
    @review.destroy
    redirect_to reviews_url, notice: 'Review was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_review
      @review = Review.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def review_params
      params.require(:review).permit(:title, :body, :image, :stars)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/home/index.html.slim
#container
  ul
    /- data["neighborhoods"].each do |neighborhood|
    /  li = neighborhood

  section#sidebar
    #fresh_reviews
      h2= link_to "Phre$h Reviews", reviews_path
      - @reviews.each do |review|
        .review
          h3
            = link_to review.title, review
            |  (#{review.stars}/5)
          img src=image_url(review.image) alt="photo of #{review.title}" height="100" width="150"
          p = review.body

  section#main
    #map
      iframe src="https://www.google.com/maps/embed?pb=!1m10!1m8!1m3!1d451863.81982580334!2d-82.58680844648437!3d27.773239669413496!3m2!1i1024!2i768!4f13.1!5e0!3m2!1sen!2sus!4v1431612800071" width="100%" height="450" frameborder="0" style="border:0"

app/views/layouts/application.html.slim
doctype html
html
  head
    title eat THIS!
    link href='http://fonts.googleapis.com/css?family=PT+Sans|PT+Serif' rel='stylesheet' type='text/css'
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags

  body
    header
      h1 eat <em>THIS!</em>

    = yield

    footer
      a href="#" Contact <em>THIS!</em>
      p Built by the May 2015 Rails Engineering cohort at The Iron Yard - Tampa/St. Petersburg

app/views/reviews/_form.html.erb
<%= form_for(@review) do |f| %>
  <% if @review.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@review.errors.count, "error") %> prohibited this review from being saved:</h2>

      <ul>
      <% @review.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>
  <div class="field">
    <%= f.label :image %><br>
    <%= f.text_field :image %>
  </div>
  <div class="field">
    <%= f.label :stars %><br>
    <%= f.number_field :stars, :max => 5, :min => 0 %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/reviews/edit.html.erb
<h1>Editing Review</h1>

<%= render 'form' %>

<%= link_to 'Show', @review %> |
<%= link_to 'Back', reviews_path %>

app/views/reviews/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Reviews</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th>Image</th>
      <th>Stars</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @reviews.each do |review| %>
      <tr>
        <td><%= review.title %></td>
        <td><%= review.body %></td>
        <td><%= review.image %></td>
        <td><%= review.stars %></td>
        <td><%= link_to 'Show', review %></td>
        <td><%= link_to 'Edit', edit_review_path(review) %></td>
        <td><%= link_to 'Destroy', review, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Review', new_review_path %>

app/views/reviews/new.html.erb
<h1>New Review</h1>

<%= render 'form' %>

<%= link_to 'Back', reviews_path %>

app/views/reviews/show.html.erb
<p id="notice"><%= notice %></p>

<h2><%= @review.display_name %></h2>

<p>
  <strong>Title:</strong>
  <%= @review.title %>
</p>

<p>
  <strong>Rating:</strong>
  <% @review.stars.times do %>⭐<% end %>
</p>


<p>
  <strong>Body:</strong>
  <%= @review.body %>
</p>

<p>
  <strong>Image:</strong>
  <%= @review.image %>
</p>

<ul>
  <% @review.comments.each do |comment| %>
    <li>
      <p><%= comment.body %></p>
      <p class="author">by <%= comment.author %> on <%= comment.created_at.to_s(:short) %></p>
      <p>
        <%= link_to "x", review_comment_path(@review, comment), { :method => :delete }  %>
      </p>
    </li>
  <% end %>
</ul>

<%= form_for(@review.comments.new, :url => review_comments_path(@review)) do |f| %>
  <div class="field">
    <%= f.label :author %><br>
    <%= f.text_field :author %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<%= link_to 'Edit', edit_review_path(@review) %> |
<%= link_to 'Back', reviews_path %>